services:
  alist:
    image: ghcr.io/monlor/xiaoya-alist:latest
    volumes:
      - xiaoya:/data
    ports:
      - "5678:5678"
      - "2345:2345"
      - "2346:2346"
    env_file:
      - env
    restart: unless-stopped
    networks:
      - default
  metadata:
    image: ghcr.io/monlor/xiaoya-metadata:latest
    environment:
      - EMBY_ENABLED=false
      - JELLYFIN_ENABLED=true
    env_file:
      - env
    volumes:
      - xiaoya:/etc/xiaoya
      - jf_media:/media/jf_xiaoya
      - jf_config:/media/jf_config
      - jf_cache:/media/jf_config/cache
      - meta:/media/temp
    depends_on:
      - alist
    restart: unless-stopped
    networks:
      - default
  jellyfin:
    image: ghcr.io/monlor/xiaoya-jellyfin:latest
    env_file:
      - env
    privileged: true
    depends_on:
      - metadata
      - alist
    volumes:
      - jf_media:/media
      - jf_config:/config
      - jf_cache:/cache
    ports:
      - 8096:8096
    restart: unless-stopped
    networks:
      - default

networks:
  default:

volumes:
  xiaoya:
  jf_media:
  jf_config:
  jf_cache:
  meta: