services:
  alist:
    image: ghcr.io/monlor/xiaoya-alist:latest
    volumes:
      - xiaoya:/data
    ports:
      - "5678:5678"
      - "2345:2345"
      - "2346:2346"
    env_file:
      - env
    restart: unless-stopped
    networks:
      - default
  metadata:
    image: ghcr.io/monlor/xiaoya-metadata:latest
    env_file:
      - env
    volumes:
      - xiaoya:/etc/xiaoya
      - media:/media/xiaoya
      - config:/media/config
      - cache:/media/config/cache
      - meta:/media/temp
    depends_on:
      - alist
    restart: unless-stopped
    networks:
      - default
  emby:
    image: ghcr.io/monlor/xiaoya-embyserver:latest
    env_file:
      - env
    depends_on:
      - metadata
      - alist
    volumes:
      - media:/media
      - config:/config
      - cache:/cache
    ports:
      - "6908:6908"
    restart: unless-stopped
    networks:
      - default

networks:
  default:

volumes:
  xiaoya:
  media:
  config:
  meta:
  cache: