version: '3.9'

services:
  alist:
    image: ghcr.io/monlor/xiaoya-alist
    volumes:
      - xiaoya:/data
    ports:
      - "5678:5678"
      - "2345:2345"
      - "2346:2346"
    env_file:
      - env
    restart: unless-stopped
    networks:
      - default
  metadata:
    image: ghcr.io/monlor/xiaoya-metadata
    environment:
      - EMBY_ENABLED=false
      - JELLYFIN_ENABLED=true
    env_file:
      - env
    volumes:
      - xiaoya:/etc/xiaoya
      - media:/media/xiaoya
      - config:/media/config
      - meta:/media/temp
    depends_on:
      - alist
    restart: unless-stopped
    networks:
      - default
  jellyfin:
    image: ghcr.io/monlor/xiaoya-jellyfin
    env_file:
      - env
    privileged: true
    devices:
      - /dev/dri:/dev/dri
    depends_on:
      - metadata
      - alist
    volumes:
      - media:/media
      - config:/config
      - cache:/cache
    ports:
      - 8096:8096
    restart: unless-stopped
    networks:
      - default

networks:
  default:

volumes:
  xiaoya:
  media:
  config:
  meta:
  cache: